# Generated by Django 5.2.4 on 2025-10-09 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_chatsphere', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aura_point',
            field=models.OneToOneField(blank=True, help_text="Reference to the user's aura points record.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_aura_point', to='core_chatsphere.aurapoints'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.OneToOneField(blank=True, help_text="Reference to the user's identity verification record.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_verification_status', to='core_chatsphere.identityverification'),
        ),
    ]
