# Generated by Django 5.2.4 on 2025-10-09 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_chatsphere', '0002_alter_user_aura_point_alter_user_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_verification_status', to='core_chatsphere.identityverification'),
        ),
    ]
