# Generated by Django 5.2.4 on 2025-10-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_chatsphere', '0003_alter_user_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
