# Generated by Django 5.2.4 on 2025-10-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_chatsphere', '0004_alter_user_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aura_point',
            field=models.IntegerField(default=0),
        ),
    ]
