# Generated by Django 5.2.4 on 2025-10-29 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_chatsphere', '0005_alter_user_aura_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aura_point',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='connection',
            name='verified',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_chatsphere.identityverification'),
        ),
    ]
