# Generated by Django 5.2.4 on 2025-10-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_chatsphere', '0006_remove_user_aura_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='verified',
        ),
    ]
