# Generated by Django 5.2.4 on 2025-10-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_chatsphere', '0008_connectionrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectionRequest',
        ),
    ]
