# Generated by Django 5.2.6 on 2026-02-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_chatsphere', '0010_dailystreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingpoints',
            name='rate_points',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
