# Generated by Django 5.2.6 on 2026-02-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_chatsphere', '0011_alter_ratingpoints_rate_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='aurapoints',
            name='last_recalculated',
            field=models.DateTimeField(blank=True, help_text='When components were last recalculated', null=True),
        ),
        migrations.AddField(
            model_name='aurapoints',
            name='rating_component',
            field=models.IntegerField(default=0, help_text='Points from star ratings'),
        ),
        migrations.AddField(
            model_name='aurapoints',
            name='report_penalty',
            field=models.IntegerField(default=0, help_text='Negative points from reports'),
        ),
        migrations.AddField(
            model_name='aurapoints',
            name='streak_component',
            field=models.IntegerField(default=0, help_text='Points from daily streak'),
        ),
        migrations.AlterField(
            model_name='aurapoints',
            name='aura_points',
            field=models.IntegerField(default=0, help_text='Total calculated Aura Points'),
        ),
    ]
