# Generated by Django 5.2.6 on 2026-02-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_chatsphere', '0012_aurapoints_last_recalculated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['receiver', 'is_read'], name='core_chatsp_receive_96f8be_idx'),
        ),
    ]
