# Generated by Django 5.2.6 on 2026-02-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_chatsphere', '0013_conversationmessage_is_read_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdentityVerification',
        ),
    ]
