# Generated by Django 5.2.6 on 2026-06-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_chatsphere', '0014_delete_identityverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
