# Generated by Django 5.2.6 on 2026-06-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_chatsphere', '0015_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, choices=[(0, 'Below 18'), (1, 'Above 18')], null=True),
        ),
    ]
