# Generated by Django 5.2.6 on 2026-06-23 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_chatsphere', '0016_alter_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('VIDEO_NSFW', 'Video NSFW'), ('TEXT_PROFANITY', 'Text Profanity')], max_length=20)),
                ('source', models.CharField(choices=[('CLIENT', 'Client-side'), ('SERVER', 'Server-side'), ('AUTO', 'Automatic System')], max_length=10)),
                ('action_taken', models.CharField(choices=[('WARNING', 'Warning Issued'), ('BLUR', 'Video Blurred'), ('DISCONNECT', 'Call Disconnected'), ('CENSORED', 'Text Censored'), ('BAN', 'User Banned')], max_length=15)),
                ('confidence', models.FloatField()),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'content_type'], name='core_chatsp_user_id_b61c2c_idx'), models.Index(fields=['created_at'], name='core_chatsp_created_6d036e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='moderation/')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='core_chatsp_user_id_e37a35_idx'), models.Index(fields=['user', 'created_at'], name='core_chatsp_user_id_81e933_idx')],
            },
        ),
    ]
